minimal_mistakes_skin: sunrise

locale: "ko-KR"
title: "개발 공부 냐미"
title_separator: " "
masthead_title: "개발자 꿈나무"
name: "Hwang-HE"
description: "관심 분야를 찾기위한 여정"
theme: minima
url : "https://hhe5361.github.io"
baseurl: "https://hhe5361.github.io/testpath"

#logo도 설정해야지 ㅎ
